[[plugins]]
  package="netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-11ty"
  [plugins.inputs]
    cache_img = './assets/images'
    cache_img_httpHeader = false

[dev]
  command = "yarn serve"
  targetPort = 4001
  publish = "_site/"

[build]
  publish = "_site/"
  command = "yarn build"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
