[[plugins]]
  package="netlify-plugin-checklinks"

[[plugins]]
  package = "netlify-plugin-11ty"
  [plugins.inputs]
    cache_img = './assets/images'
    cache_img_httpHeader = false

[[redirects]]
  from = "https://necipsunmaz.netlify.app/*"
  to = "https://necipsunmaz.com/:splat"
  status = 301
  force = false

[dev]
  command = "yarn serve"
  targetPort = 4001
  publish = "_site/"

[build]
  publish = "_site/"
  command = "yarn build"
